# Generated by Django 4.1.2 on 2024-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autores', models.AutoField(db_column='idAutores', primary_key=True, serialize=False)),
                ('nom_autores', models.CharField(max_length=50)),
                ('nac_autores', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categorias', models.AutoField(db_column='idCategorias', primary_key=True, serialize=False)),
                ('nom_categorias', models.CharField(max_length=100)),
                ('descrip_categorias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='idLibro', primary_key=True, serialize=False)),
                ('nom_libro', models.CharField(max_length=100)),
                ('annio_libro', models.CharField(max_length=50)),
                ('descrip_libro', models.CharField(max_length=200)),
            ],
        ),
    ]
