# Generated by Django 4.1.2 on 2024-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_autores_categorias_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descrip_libro',
            field=models.CharField(max_length=1000),
        ),
    ]
